site_name: Teiva Harsanyi
site_url: https://teivah.dev
repo_name: teivah/teivah.dev
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
nav:
  - index.md
  - jobs.md
