site_name: Teiva Harsanyi
site_url: https://teivah.dev
repo_name: teivah/teivah.dev
theme:
  name: material
  favicon: img/devoxx.png
  icon:
    logo: material/coffee
    admonition:
      tip: material/format-quote-close
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: blue
    accent: orange
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: blue grey
    accent: grey
nav:
  - 'Teiva Harsanyi': index.md
  - newsletter.md
  - book.md
  - talks.md
  - resources.md
  - contact.md
plugins:
- glightbox
- redirects:
    redirect_maps:
      'blog.md': 'https://teivah.medium.com/'
      'confoo-reliability.md': 'https://teivah.dev/talks/#4-reliability-anti-patterns-confoo-conference'
      'confoo-aoc.md': 'https://teivah.dev/talks/#i-completed-all-9-advents-of-code-lessons-learned-confoo-conference'
      'devoxx.md': 'https://teivah.dev/talks/#jai-termine-les-9-advents-of-code-lecons-apprises-devoxx-france-conference'
      'foo.md': 'https://gist.github.com/teivah/ff2cdc20a7a562e65f953990fd51b8de'
extra:
  generator: false
  analytics:
    provider: google
    property: G-YK142LCQX3
markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; 2016 - 2024 Teiva Harsanyi
extra_css:
- style.css