site_name: Teiva Harsanyi
site_url: https://teivah.dev
repo_name: teivah/teivah.dev
theme:
  name: material
  favicon: img/avatar.jpg
  icon:
    logo: material/coffee
  custom_dir: overrides
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: blue
    accent: orange
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: blue grey
    accent: grey
nav:
  - index.md
  - book.md
  - talks.md
  - interview.md
  - contact.md
plugins:
- redirects:
    redirect_maps:
      'blog.md': 'https://teivah.medium.com/'
      'confoo-reliability.md': 'https://docs.google.com/presentation/d/e/2PACX-1vSliUbEggyAxG6lXczPtR_lGRR5UIURiEJ3mlyf9Hlw-BNcfxloTWIPcwjmxeAgGxbnIAyodtpuLkEc/pub?start=false&loop=false'
      'confoo-aoc.md': 'https://docs.google.com/presentation/d/e/2PACX-1vS4opZu2emQk76w2u1PD9YZxOpbCY8I-qWbKY6USTCrlHAGlvfirktuINnJKtCwMR3QBpt4-ayLXqQ2/pub?start=false&loop=false'
extra:
  generator: false
markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; 2016 - 2024 Teiva Harsanyi
extra_css:
- style.css